version = 0.1
[default.deploy.parameters]
stack_name = "interphlix"
# resolve_s3 = true
s3_bucket = "interphlix-code"
region = "us-east-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
