name: Deploy to AWS

on:
  workflow_dispatch:
  push:
    branches:
      - main  # Adjust to the branch you want to trigger the deployment

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          
      - name: Install Zig toolchain
        uses: korandoru/setup-zig@v1
        with:
          zig-version: 0.10.0

      - name: Install Cargo Lambda
        run: cargo install cargo-lambda

      - name: Install arm64 target
        run: rustup target add aarch64-unknown-linux-gnu

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.5  # Adjust the Python version as needed

      - name: Install AWS CLI and SAM CLI
        run: |
          pip install awscli
          pip install aws-sam-cli

      - name: Configure AWS CLI
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set region ${{ secrets.AWS_REGION }}

      - name: Compile Rust Code
        run: cargo lambda build --release --output-format zip --arm64

      - name: Package SAM application
        run: sam package --template-file template.yaml --output-template-file packaged.yaml --s3-bucket interphlix-code

      - name: Deploy SAM application
        run: sam deploy --template-file packaged.yaml --stack-name interphlix
